# Generated by Django 3.2.3 on 2021-06-06 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('photo', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ExpoPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, default='', max_length=200)),
                ('photos', models.FileField(upload_to='expophotos/')),
                ('expo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='exhibitions.expo')),
            ],
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
