# Generated by Django 3.2.3 on 2021-05-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_cloudinary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='Tittle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
