# Generated by Django 3.2 on 2021-04-26 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the painting's category (e.g. Sketch, Study, Drawing, Painting, etc.)", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the painting's category (e.g. Genève, Alger, etc.)", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a medium used to paint (e.g. ink, acrylic etc.)', max_length=205)),
            ],
        ),
        migrations.CreateModel(
            name='Painter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='died')),
                ('image', models.FilePathField(blank=True, help_text="Painter's portrait", null=True, path='catalog/static/images')),
                ('biography', models.TextField(blank=True, help_text="Describe painter's biography", null=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the painting's surface (e.g. canvas, wood etc.)", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the painting's tags (e.g. boats, family, mountains, etc.)", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Enter a brief description of the Painting', max_length=1000)),
                ('motif', models.CharField(blank=True, choices=[('ge', 'Genre painting (everyday life)'), ('por', 'Portrait'), ('apa', 'Autoportrait'), ('la', 'Landscape'), ('nm', 'Still life'), ('ot', 'Other')], help_text='The subject-matter', max_length=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images/')),
                ('date', models.DateField(blank=True, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=20, null=True)),
                ('signature', models.BooleanField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, help_text="Enter any re2mark that doesn't match any other category", max_length=200, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='catalog.category')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.location')),
                ('medium', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.medium')),
                ('painter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.painter')),
                ('support', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.support')),
                ('tag', models.ManyToManyField(help_text='Select tags for this painting', to='catalog.Tag')),
            ],
            options={
                'ordering': ['title', 'painter'],
            },
        ),
    ]
