# Generated by Django 3.2.3 on 2021-05-29 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting',
            name='dimensions',
        ),
        migrations.AddField(
            model_name='painter',
            name='pitch',
            field=models.TextField(blank=True, help_text="Pitch pour capter l'attention", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='painting',
            name='hauteur',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='painting',
            name='largeur',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='painting',
            name='reference',
            field=models.CharField(blank=True, help_text='ref. orinal noté par Jean-Marie', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='painter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='painting',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='catalog.category'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a brief description of the Painting', max_length=1000),
        ),
        migrations.AlterField(
            model_name='painting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='painting',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.location'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='medium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.medium'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='remark',
            field=models.TextField(blank=True, help_text="Enter any remark that doesn't match any other category", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='painting',
            name='support',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.support'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='tag',
            field=models.ManyToManyField(blank=True, help_text='Select tags for this painting', to='catalog.Tag'),
        ),
    ]
