# Generated by Django 3.2 on 2021-04-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a brief description of the Painting', max_length=1000),
        ),
    ]
