# Generated by Django 3.2 on 2021-04-26 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_painting_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.location'),
        ),
    ]
