# Generated by Django 3.2.3 on 2021-05-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_painting_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='painters/'),
        ),
    ]
