# Generated by Django 3.2.3 on 2021-05-30 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_painter_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='painter',
            options={},
        ),
    ]
