# Generated by Django 3.2 on 2021-04-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_painting_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painter',
            name='image',
            field=models.FilePathField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='painting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
