# Generated by Django 3.2 on 2021-04-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20210427_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
