# Generated by Django 3.2 on 2021-05-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_painting_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='tag',
            field=models.ManyToManyField(blank=True, help_text='Select tags for this painting', null=True, to='catalog.Tag'),
        ),
    ]
