# Generated by Django 3.2 on 2021-05-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_painting_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting',
            name='dimensions',
        ),
        migrations.AddField(
            model_name='painting',
            name='hauteur',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='painting',
            name='largeur',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='painting',
            name='reference',
            field=models.CharField(blank=True, help_text='ref. orinal noté par Jean-Marie', max_length=10, null=True),
        ),
    ]
