# Generated by Django 3.2.2 on 2021-05-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20210505_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='painter',
            name='pitch',
            field=models.TextField(blank=True, help_text="Describe painter's biography", max_length=500, null=True),
        ),
    ]
